server:
  port: 8080

spring:
  devtools:
    restart:
      enabled: true
    livereload:
      enabled: true
  application:
    name: backend-projectbase
  datasource:
    url: jdbc:mariadb://localhost:3306/base
    username: baseadm
    password: 1234

mybatis:
  mapper-locations: classpath:mapper/**/*.xml

logging:
  level:
    org.apache.ibatis: DEBUG
    org.mybatis.spring.mapper: DEBUG
    org.springframework.http.converter: DEBUG

