server:
  port: 8080

spring:
  devtools:
    restart:
      enabled: true
    livereload:
      enabled: true
  application:
    name: backend-projectbase
  datasource:
    url: jdbc:mariadb://localhost:3306/base
    username: baseadm
    password: 1234

decorator:
  datasource:
    p6spy:
      enabled: true    # 데코레이터 확실히 켜기
      
mybatis:
  mapper-locations: classpath:mapper/**/*.xml
  # configuration:
  #   log-impl: org.apache.ibatis.logging.slf4j.Slf4jImpl


logging:
  level:
    # org.apache.ibatis: DEBUG
    # org.springframework.http.converter: DEBUG
    # base.work: TRACE
    p6spy: INFO


