server:
  port: 8080

spring:
  devtools:
    restart:
      enabled: true
    livereload:
      enabled: true
  application:
    name: backend-projectbase
  datasource:
    common:
      driver-class-name: org.postgresql.Driver
      jdbc-url: jdbc:postgresql://172.22.112.1:5432/coredb?currentSchema=common
      username: app_user
      password: 1234
      maximum-pool-size: 10
      minimum-idle: 2
      idle-timeout: 30000
      connection-timeout: 20000
      max-lifetime: 1800000
  
  jpa:
    hibernate:
      ddl-auto: none  # validate / update / create-drop 등 필요에 따라 설정
    properties:
      hibernate:
        format_sql: true
        show_sql: true

mybatis:
  mapper-locations: classpath:mapper/**/*.xml
  type-aliases-package: com.base.domain
decorator:
  datasource:
    p6spy:
      enabled: true    # 데코레이터 확실히 켜기

logging:
  level:
    # org.apache.ibatis: DEBUG
    # org.springframework.http.converter: DEBUG
    # base.work: TRACE
    p6spy: INFO


jwt:
  secret: ${JWT_SECRET:change-me-change-me-change-me-change-me-123456}
  access-token-expiration-seconds: ${JWT_ACCESS_TOKEN_EXPIRATION_SECONDS:3600}

# application.yml
cors:
  allowed-origins:
    - "http://localhost:5173"
  allowed-methods: ["GET","POST","PUT","PATCH","DELETE","OPTIONS"]
  allowed-headers: ["Authorization","Content-Type"]
  exposed-headers: ["Authorization"]
  allow-credentials: false   # 쿠키 쓸 때 true
  max-age: 3600
