server:
  port: 8080

spring:
  application:
    name: backend-projectbase
  datasource:
    url: jdbc:mariadb://localhost:3306/base
    username: baseadm
    password: 1234

mybatis:
  mapper-locations: classpath:mapper/**/*.xml